name: Upmerge release branches

# Schedule this workflow to run every 15 minutes
on:
  workflow_dispatch:
  # Trigger on new commits to release branches
  push:
   branches: [ "**" ]
jobs:
  trigger-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [ codespaces-actions-playground ]
    steps:
      - name: Creteate pull requests to upmerge branches to main
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACAS_WORKFLOWS_TOKEN }}
          script: |
            // Get all protected branches
            const protectedBranches = await github.rest.repos.listBranches({
              owner: "brianbolt",
              repo: "${{ matrix.repo }}",
              protected: true
            })
            // Print all the protected branches
            console.log(protectedBranches.data.map(branch => branch.name))
            // Sort the branches by name but always have master or main at the end
            protectedBranches.data.sort((a, b) => {
              if (a.name === "master" || a.name === "main") {
                return 1
              }
              if (b.name === "master" || b.name === "main") {
                return -1
              }
              return a.name.localeCompare(b.name)
            })
            // Shift through the branches and create a pull request for each to the next branch in the list
            for (let i = 0; i < protectedBranches.data.length - 1; i++) {
              const sourceBranch = protectedBranches.data[i].name
              const targetBranch = protectedBranches.data[i + 1].name
              console.log(`Creating pull request from ${sourceBranch} to ${targetBranch}`)
              // Check if there are diffs between the 2 branches
              const diff = await github.rest.repos.compareCommits({
                owner: "brianbolt",
                repo: "${{ matrix.repo }}",
                base: targetBranch,
                head: sourceBranch
              })
              if (diff.data.files.length === 0) {
                console.log(`No diffs between ${sourceBranch} and ${targetBranch}`)
                continue
              }
              // Check if a pull request already exists for these branches
              const pullRequests = await github.rest.pulls.list({
                owner: "brianbolt",
                repo: "${{ matrix.repo }}",
                state: "open",
                head: sourceBranch,
                base: targetBranch
              })
              // Delete the pull request if it already exists
              if (pullRequests.data.length > 0) {
                console.log(`Deleting pull request ${pullRequests.data[0].number}`)
                // Write a comment first then close it
                await github.rest.issues.createComment({
                  owner: "brianbolt",
                  repo: "${{ matrix.repo }}",
                  issue_number: pullRequests.data[0].number,
                  body: "This pull request was closed because it has been superseded by another pull request."
                })
                await github.rest.pulls.update({
                  owner: "brianbolt",
                  repo: "${{ matrix.repo }}",
                  pull_number: pullRequests.data[0].number,
                  state: "closed"
                })
              }
              // Create a unique set of reviewers: Reviewers for the PR should be anyone with commits in the diff 
              const reviewers = diff.data.commits.map(commit => commit.author.login)
              // Remove any duplicate reviewers
              const uniqueReviewers = [...new Set(reviewers)]
              // If brian bolt is a reviewer, remove him but tag him in the description
              add_brianbolt = false
              if (uniqueReviewers.includes("brianbolt")) {
                console.log("Removing brianbolt from reviewers because he can't create the pr and review it at the same time")
                uniqueReviewers.splice(uniqueReviewers.indexOf("brianbolt"), 1)
                add_brianbolt = true
              }
              // Create the description for the pull request
              const description = "## Description\n\n" +
                "This pull request was created by the upmerge workflow.\n\n" +
                "## Reviewers\n\n" +
                uniqueReviewers.map(reviewer => `@${reviewer}`).join(" ") + "\n\n" +
                (add_brianbolt ? "@brianbolt" : "")
              // Create the pull request
              const pullRequest = await github.rest.pulls.create({
                owner: "brianbolt",
                repo: "${{ matrix.repo }}",
                title: `Upmerge ${sourceBranch} to ${targetBranch}`,
                body: description,
                head: sourceBranch,
                base: targetBranch
              })
              // Add the upmerge label to the pull request
              await github.rest.issues.addLabels({
                owner: "brianbolt",
                repo: "${{ matrix.repo }}",
                issue_number: pullRequest.data.number,
                labels: ["upmerge"]
              })
              // Add the reviewers to the pull request if there are any
              if (uniqueReviewers.length > 0) {
                await github.rest.pulls.requestReviewers({
                  owner: "brianbolt",
                  repo: "${{ matrix.repo }}",
                  pull_number: pullRequest.data.number,
                  reviewers: uniqueReviewers
                })
              }
              console.log(`Created pull request ${pullRequest.data.number}`)
            }