name: Upmerge release branches

# Schedule this workflow to run every 15 minutes
on:
  workflow_dispatch:
  # Trigger on new commits to release branches
  push:
   branches: [ "**" ]
jobs:
  trigger-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [ codespaces-actions-playground ]
    steps:
      - name: Creteate pull requests to upmerge branches to main
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACAS_WORKFLOWS_TOKEN }}
          script: |
            // Get all protected branches
            const protectedBranches = await github.rest.repos.listBranches({
              owner: "brianbolt",
              repo: "${{ matrix.repo }}",
              protected: true
            })
            // Print all the branch
            console.log(protectedBranches.data.map(branch => branch.name))
